# Generated by Django 4.2.8 on 2025-06-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_task_student_task_deadline_alter_task_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignedtask',
            table='tbl_assigned_task',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tbl_task',
        ),
    ]
