# Generated by Django 4.2.8 on 2025-06-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_assignedtask_table_alter_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
