# Generated by Django 4.2.8 on 2025-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_section_student_section_task_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
