# Generated by Django 4.2.8 on 2025-06-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_remove_section_section_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
