# Generated by Django 4.2.8 on 2025-06-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_task_section_assignedtask_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
