# Generated by Django 4.2.8 on 2025-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
