# Generated by Django 4.2.8 on 2025-06-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.section'),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.section'),
        ),
    ]
