# Generated by Django 4.2.8 on 2025-06-15 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_assignedtask_section_alter_task_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
