# Generated by Django 4.2.8 on 2025-06-15 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_assignedtask_created_at_assignedtask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
